---
- name: Create GFS2 FS on node pcm1 and syncronize it on all cluster nodes
  become: true
  hosts: pcm1
  tasks:
    - name: Create cluster lvm
      shell: >
        pvcreate /dev/sdc &&
        vgcreate -Ay -cy cluster_vg /dev/sdc &&
        lvcreate -l100%FREE -n cluster_lv cluster_vg
    - name: Create gfs2 FS
      shell: >
        echo y | mkfs.gfs2 -j3 -p lock_dlm -t gfs2-cluster:gfs2 /dev/cluster_vg/cluster_lv
    - name: Pacemaker resource create
      shell: >
        pcs resource create clusterfs Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2" \
        fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=ignore clone interleave=true
    - name: Constraint order and colocation
      shell: >
        pcs constraint order start clvmd-clone then clusterfs-clone &&
        pcs constraint colocation add clusterfs-clone with clvmd-clone
- name: Results
  become: true
  hosts: pcm
  tasks:   
    - name: "Show result:"
      shell: lsblk
      register: results
    - name: It's work!
      debug:
        var: results

      